site_name: AffineLab Knowledge Docs
site_description: A knowledge base for sharing insights on selected technical topics. Built with MkDocs.
site_url: !ENV [SITE_URL, "http://127.0.0.1:8000/"]
site_dir: site

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.page.meta

  palette:
    # nightmode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式

    # sunnymode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到明亮模式

nav:
  - Home: index.md
  - AimeManual:
      - MonicaLite: AimeManual/MonicaLite.md

plugins:
  - search
  - i18n:
      languages:
        - locale: zh
          name: 中文
          default: true
          build: true
        - locale: en
          name: English
          build: true
  - git-revision-date-localized:
      type: datetime
      locale: zh


extra:
  alternate:
    - name: 中文
      link: !ENV [SITE_URL_ZH, "http://127.0.0.1:8000/"]
      lang: zh
    - name: English
      link: !ENV [SITE_URL, "http://127.0.0.1:8000/en/"]
      lang: en
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 1-4
  - pymdownx.details